api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views

app_name = 'api'

router = routers.DefaultRouter()

urlpatterns = [
    path('', include(router.urls)),
    path('city-counts/', views.CityCountView.as_view(), name='city-counts'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
    path('users/', include('user.urls')),
    path('api/', include('api.urls')),
]

user/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LogoutView

app_name = 'user'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

weather/urls.py
from . import views
from django.urls import path

app_name = 'weather'

urlpatterns = [
    path('', views.WeatherView.as_view(), name='index'),
]

api/models.py
from django.db import models

# Create your models here.

weather/models.py
from django.db import models
from django.contrib.auth.models import User

from weather.utils import AbstractModel


class SearchHistory(AbstractModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=100)

    def __str__(self):
        return f"Пользователь: {self.user.username}, город: {self.city}"

user/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))
    
    class Meta:
        model = User
        fields = ('username', 'password')

    
class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(label='Подтвердите пароль', widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Подтвердите пароль'}))
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

weather/forms.py
# weather/forms.py
from django import forms

class CityForm(forms.Form):
    city = forms.CharField(max_length=100, label='Город', widget=forms.TextInput(attrs={
        'placeholder': 'Введите название города',
        'label': 'Город',
    }))

api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.db.models import Count
from weather.models import SearchHistory
from weather.serializers import CityCountSerializer


class CityCountView(APIView):
    def get(self, request):
        city_counts = SearchHistory.objects.values('city').annotate(count=Count('city')).order_by('-count')
        serializer = CityCountSerializer(city_counts, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

common/views.py
class TitleMixin:
    title = None

    def get_context_data(self, **kwargs):
        context = super(TitleMixin, self).get_context_data(**kwargs)
        context["title"] = self.title
        return context


class WeatherTitleMixin:
    title = None

    def get_title(self):
        return self.title

user/views.py
from django.shortcuts import render
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User

from common.views import TitleMixin
from user.forms import UserLoginForm, UserRegistrationForm


class UserLoginView(TitleMixin, LoginView):
    template_name = 'user/login.html'
    form_class = UserLoginForm
    title = 'Авторизация'


class UserRegistrationView(TitleMixin, SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'user/registration.html'
    success_url = reverse_lazy('user:login')
    success_message = 'Регистрация прошла успешно!'
    title = 'Регистрация'

weather/views.py
from django.views import View
from django.shortcuts import render

from common.views import TitleMixin, WeatherTitleMixin
from .forms import CityForm
from .utils import get_weather
from .models import SearchHistory

class WeatherView(WeatherTitleMixin, View):
    form_class = CityForm
    template_name = 'weather/index.html'
    title = 'Погода'
    
    def get(self, request):
        form = self.form_class()
        weather_data = None
        last_city = None

        if request.user.is_authenticated:
            last_city = SearchHistory.objects.filter(user=request.user).last()

        city = request.GET.get('city')
        if city:
            form = self.form_class(initial={'city': city})
            weather_data = get_weather(city)

        return render(request, self.template_name, {
            'form': form,
            'weather_data': weather_data,
            'last_city': last_city,
            'title': self.get_title()
        })

    def post(self, request):
        form = self.form_class(request.POST)
        last_city = None

        if request.user.is_authenticated:
            history = SearchHistory.objects.filter(user=request.user).order_by('-created_at')
            if history.count() > 1:
                last_city = history[1]

        if form.is_valid():
            city = form.cleaned_data['city']
            weather_data = get_weather(city)
            if request.user.is_authenticated:
                SearchHistory.objects.create(user=request.user, city=city)
                history = SearchHistory.objects.filter(user=request.user).order_by('-created_at')
                if history.count() > 1:
                    last_city = history[1]
            return render(request, self.template_name, {
                'form': form,
                'weather_data': weather_data,
                'last_city': last_city,
                'title': self.get_title()
            })
        return render(request, self.template_name, {
            'form': form,
            'last_city': last_city,
            'title': self.get_title()
        })

user/templates/user/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    {% if messages %}
        {% for message in messages %} {{ message }} {% endfor %}
    {% endif %}
    <h1>Логин</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Войти!</button>
    </form>
</body>
</html>

user/templates/user/registration.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>Заполните форму ниже:</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Регистрация!</button>
    </form>
</body>
</html>

weather/templates/weather/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    {% if user.is_authenticated %}
        <h1>Привет, @{{ user.username }}!</h1>
        <a href="{% url 'user:logout' %}">Выйти?</a>
    {% else %}
        <h1>Привет, без регистрации функционал ограничен!</h1>
        <li>
            <a href="{% url 'user:login' %}">Войти</a>
        </li>
        <li>
            <a href="{% url 'user:registration' %}">Регистрация</a>
        </li>
    {% endif %}
    <h2>API:</h2>
    <a href="{% url 'api:city-counts' %}">/api/city-counts/</a>
    <h1>Прогноз погоды в вашем городе:</h1>
    {% if last_city %}
        <h2>Ваш последний запрос: <a href="?city={{ last_city.city }}">{{ last_city.city }}</a></h2>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Найти!</button>
    </form>
    {% if weather_data %}
        <h2>Погода в {{ weather_data.city }}</h2>
        {% for day in weather_data.forecast %}
            <h3>{{ day.day }}</h3>
            <p>Максимальная температура: {{ day.max_temp }}°C</p>
            <p>Минимальная температура: {{ day.min_temp }}°C</p>
            <p>Осадки: {{ day.precipitation }} мм</p>
        {% endfor %}
    {% endif %}
</body>
</html>